# Generated by Django 3.0.7 on 2020-08-09 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('overview', models.TextField(blank=True, default='You have no an Overview yet')),
                ('city', models.CharField(default='USA', max_length=20)),
                ('phone', models.IntegerField(blank=True, default=0)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=10)),
                ('skill', models.CharField(default='You have no skills yet', max_length=100)),
                ('logo', models.ImageField(blank=True, default='images/default-logo.jpg', upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
