# Generated by Django 3.1.1 on 2020-10-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='community.comment'),
        ),
    ]
