# Generated by Django 3.1.1 on 2020-10-14 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0005_notification_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_comment', models.ManyToManyField(related_name='like_notif_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
