# Generated by Django 3.1.1 on 2020-10-15 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0006_likenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notify_comment',
            field=models.ManyToManyField(blank=True, related_name='notify_comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikeNotification',
        ),
    ]
