# Generated by Django 3.1.1 on 2020-10-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20201015_0430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
